use_frameworks! # Add this if you are targeting iOS 8+ or using Swift
platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

pod 'Metawear-iOSAPI'
pod 'CocoaAsyncSocket'  
pod 'AFNetworking', '~> 2.0'